"""empty message

Revision ID: bfab78679454
Revises: 
Create Date: 2019-09-03 15:14:15.976122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfab78679454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_table('guest',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('handicap', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=75), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.club_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_round',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('hole_1_score', sa.Integer(), nullable=True),
    sa.Column('hole_2_score', sa.Integer(), nullable=True),
    sa.Column('hole_3_score', sa.Integer(), nullable=True),
    sa.Column('hole_4_score', sa.Integer(), nullable=True),
    sa.Column('hole_5_score', sa.Integer(), nullable=True),
    sa.Column('hole_6_score', sa.Integer(), nullable=True),
    sa.Column('hole_7_score', sa.Integer(), nullable=True),
    sa.Column('hole_8_score', sa.Integer(), nullable=True),
    sa.Column('hole_9_score', sa.Integer(), nullable=True),
    sa.Column('hole_10_score', sa.Integer(), nullable=True),
    sa.Column('hole_11_score', sa.Integer(), nullable=True),
    sa.Column('hole_12_score', sa.Integer(), nullable=True),
    sa.Column('hole_13_score', sa.Integer(), nullable=True),
    sa.Column('hole_14_score', sa.Integer(), nullable=True),
    sa.Column('hole_15_score', sa.Integer(), nullable=True),
    sa.Column('hole_16_score', sa.Integer(), nullable=True),
    sa.Column('hole_17_score', sa.Integer(), nullable=True),
    sa.Column('hole_18_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.guest_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('round_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_round')
    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('guest')
    op.drop_table('club')
    # ### end Alembic commands ###
